<a href="https://colab.research.google.com/github/teddcp/numpy-notes/blob/master/numpy_notes_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#numpy stores data of one type
#in the below examle, all are comverted to string 
import numpy as np
a=np.array(['tedd',11,12.35,True])
print(a)
print(a.dtype)

['tedd' '11' '12.35' 'True']
<U5


In [6]:
print(np.zeros(4,dtype=int))
print(np.zeros((1,4),dtype=int))

[0 0 0 0]
[[0 0 0 0]]


# Numpy's Structured/Record arrays
-------------------------------------------

Numpy is used for to store the homogenous data i.e all the elements of same data type. Even if we try to store diff. data type in numpy array, it will cast them to a common data type.

But we need sometimes to store hetrogenous data. Here the structured arrays help us to achieve this.To do that we use the **compound datatype** of numpy.

In [0]:
 name = ['Alice', 'Bob', 'Cathy', 'Doug']       
 age = [25, 45, 37, 19]       
 weight = [55.0, 85.5, 68.0, 61.5] 

In [9]:
# using  a compound data type to store all the above data into a single structure
data=np.zeros(4,dtype={'names':('name','age','weight'), 'formats':('U10','i4','f8')})
data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
data['name']=name
data['age']=age
data['weight']=weight

# all the different data are arranged in a single block of memory
data

array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
       ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

# Accessing the elements inside structured arrays

> data[key_name]

> data[index]

> data[index][index]

boolean masking also works here.

In [12]:
data.size

4

In [15]:
data[0],data[-1]  #accessing the elements index wise

(('Alice', 25, 55.), ('Doug', 19, 61.5))

In [16]:
data['name'],data['weight']   #accessing the field names : name,age,weight

(array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10'),
 array([55. , 85.5, 68. , 61.5]))

In [18]:
data[0][-1]   #selecting the last element of first element i.e ('Alice', 25, 55.)

55.0

In [21]:
data[-1]['name']  # we combine the index and name format as well

'Doug'

In [28]:
data[data['age']>20 ]['name']  #boolean masking 

array(['Alice', 'Bob', 'Cathy'], dtype='<U10')

In [30]:
#Note : Complex operations won't support here like bit operations : &,|,~
#solution : pandas DataFrame
data[ data['age']>30 & data['weight']<50 ]

TypeError: ignored

## alternative way to create a structured arrays

In [33]:
# 1: passing in dictionary : the field name and data type
dt=np.dtype({'names':('name','age'),'formats':('S10','i8')} )
arr=np.zeros(2,dtype=dt)
arr

array([(b'', 0), (b'', 0)], dtype=[('name', 'S10'), ('age', '<i8')])

In [38]:
# 2: passing in list of tuples
dt=np.dtype([('name','U10'),('roll_no','i8'),('age','i8')])
arr=np.zeros(5,dtype=dt)
print(arr)

[('', 0, 0) ('', 0, 0) ('', 0, 0) ('', 0, 0) ('', 0, 0)]


In [40]:
# 3: without field names ,it assigns default field name : f0,f1,f2 etc
dt=np.dtype('S10,i4,f8')
arr=np.zeros(4,dtype=dt)
arr

array([(b'', 0, 0.), (b'', 0, 0.), (b'', 0, 0.), (b'', 0, 0.)],
      dtype=[('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

## Record arrays

fields can be accessed as attributes rather than as dictionary keys with the 
**np.recarray** class.

The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax. 


In [42]:
data_rec=np.recarray((3,2),dtype=[('x','int'),('y','float')])
data_rec

rec.array([[(    73726016, 2.05833592e-312),
            (171798691956, 2.05833592e-312)],
           [(442381631602, 9.33678149e-313),
            (180388626464, 2.27053550e-312)],
           [(416611827831, 2.18565567e-312),
            (176093659251, 2.66090406e-312)]],
          dtype=[('x', '<i8'), ('y', '<f8')])

In [44]:
#convert a ndarray to recarray by view
data_rec=data.view(np.recarray)
data_rec   # itss a record array

rec.array([('Alice', 25, 55. ), ('Bob', 45, 85.5), ('Cathy', 37, 68. ),
           ('Doug', 19, 61.5)],
          dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [46]:
data_rec.name  # accessing via dot attribute to field 

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')