<a href="https://colab.research.google.com/github/teddcp/numpy-notes/blob/master/Numpy_notes_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Tutorial**


---





Differece between list and numpy

To be discussed ....

In [0]:
import numpy as np

In [0]:
np.__version__      # GETTING THE VERSION OF NUMPY

'1.18.3'

In [0]:
#@ creating a 1-d numpy array /vector
a=np.array([1,2,3])
print('\n',a)

#@ creating a 2-d numpy array
b=np.array([ [2,3,4],
             [4,5,6],
             [2,2,2]
           ])
print('\n',b)

#@ creating a 3-d numpy array
c=np.array([ [
              [1,2,4],
              [3,5,7]
             ],
             [
              [7,8,9],
              [10,11,13]
             ] 
           ])
print('\n',c)
print('\n',type(c))


 [1 2 3]

 [[2 3 4]
 [4 5 6]
 [2 2 2]]

 [[[ 1  2  4]
  [ 3  5  7]]

 [[ 7  8  9]
  [10 11 13]]]

 <class 'numpy.ndarray'>


# 2. we can get the **below details** from an numpy array i.e **ndarray**. 

1.  shape : array.shape
2.  dimension : array.ndim
3.  size : array.Size
4.  datatype: array.dtype
5.  nbytes : array.nbytes

**for **1-dim**, shape returns the length of array as tuple

In [0]:
# getting the shape of arrays
print(a.shape,b.shape,c.shape)

#getting the dimension
print(a.ndim,b.ndim,c.ndim)

#getting the size
print(a.size,b.size,c.size)

#getting the datatype
print(a.dtype,b.dtype,c.dtype)

#getting the total bytes of the array
print(a.nbytes,b.nbytes,c.nbytes)

#getting itemsize of each element of an array
print(a.itemsize)

(3,) (3, 3) (2, 2, 3)
1 2 3
3 9 12
int64 int64 int64
24 72 96
8


# 3. reshape() vs resize()

> reshape vs resize

reshape does not change the original array while resize does



In [0]:
b.reshape(1,9)

array([[2, 3, 4, 4, 5, 6, 2, 2, 2]])

In [0]:
b   # while b did not get changed...

array([[2, 3, 4],
       [4, 5, 6],
       [2, 2, 2]])

In [0]:
b.resize(1,9)

In [0]:
b,b.ndim  #b did get changed...

(array([[2, 3, 4, 4, 5, 6, 2, 2, 2]]), 2)

In [0]:
# getting back to the original size
b.resize(3,3)
b

array([[2, 3, 4],
       [4, 5, 6],
       [2, 2, 2]])

# 4. converting list/tuple to numpy array

In [0]:
l=[1,2,43]
print(l,type(l))

demo=np.array(l)
print(demo,type(demo))

demo=(4,5,6)
print(demo,type(demo))
print(np.array(demo), type(demo))

[1, 2, 43] <class 'list'>
[ 1  2 43] <class 'numpy.ndarray'>
(4, 5, 6) <class 'tuple'>
[4 5 6] <class 'tuple'>


# 5. change the datatype

a.dtype

In [0]:
a.dtype

dtype('int64')

In [0]:
a.dtype='int'
a

array([1, 2, 3])



1.   np.zeros(size_tuple,dtype),
     np.zeros_like(array_ref,dtype)

2.   np.ones(size_tuple,dtype)
     np.ones_like(array_ref,dtype)

3.   np.full(size_tuple,dtype,fill_value)
     np.full_like(tuple_size,fill_value,dtype)

4.   np.arange(start,end,step) #end is excluded

     (evenly spaced elements between a and b)
5.   np.linspace(a,b,number_of_values) 

6.   np.random.random(size_tuple)) 
     
     np.random.rand(row_sz,col_sz)

    creates a uniformly distributed values between 0 and 1

7.  np.random.uniform(low,high,size_tuple)
    
    creates a uniformed distribution between low and high of specified size

8. np.random.normal(mean,std_dev,size_tuple) 
   
   np.random.randn(row_sz,col_sz)

    creates a normal distribution of specified mean and stanard deviation

9.  np.random.randint(start,end,size_tuple)

    creates a random intervals with specified size  in the interval of [a,b)

10. np.eye(size) : creates an identitiy function of sizeXsize

11. np.empty(size) : 
    
    Create an uninitialized array of specified size and The values will be  whatever happens to already exist at that memory location 
 

In [0]:
#zeros matrix
print(np.zeros(10,dtype='int'))
print(np.zeros((3,2),dtype='int'))
print(np.zeros_like(b,dtype='float'))

[0 0 0 0 0 0 0 0 0 0]
[[0 0]
 [0 0]
 [0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
# ones matrix
print(np.ones(10,dtype='int'))
print(np.ones((3,2),dtype='int'))
print(np.ones_like(b,dtype='float'))

[1 1 1 1 1 1 1 1 1 1]
[[1 1]
 [1 1]
 [1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
# full matrix
print(np.full(10,fill_value=10))
print(np.full((3,2),dtype='int',fill_value=100))
print(np.full_like(b,dtype='float',fill_value=90))

[10 10 10 10 10 10 10 10 10 10]
[[100 100]
 [100 100]
 [100 100]]
[[90. 90. 90.]
 [90. 90. 90.]
 [90. 90. 90.]]


In [0]:
#identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [0]:
#random arrays
np.random.seed(42)
np.random.randint(10,20,(3,4))

array([[16, 13, 17, 14],
       [16, 19, 12, 16],
       [17, 14, 13, 17]])

In [0]:
np.random.seed(100)
np.random.rand(4,2)

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613],
       [0.00471886, 0.12156912],
       [0.67074908, 0.82585276]])

In [0]:
np.random.randn(4,3)

array([[ 0.22117967, -1.07004333, -0.18949583],
       [ 0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081],
       [-0.10441114, -0.53128038,  1.02973269]])

In [0]:
demo=np.arange(2,10)
demo

array([2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
demo[0],demo[-1],demo[3::-1],demo[::-2],demo[1:3],demo[0:4:2]

(2, 9, array([5, 4, 3, 2]), array([9, 7, 5, 3]), array([3, 4]), array([2, 4]))