<a href="https://colab.research.google.com/github/teddcp/numpy-notes/blob/master/summary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import numpy as np
print(np.__version__)

1.18.3


#data types and attributes
--------------------------------------

main data type is ndarray

In [103]:
# 1-dimensional
a=np.array([1,2,3])
a

array([1, 2, 3])

array([1, 2, 3])

In [104]:
type(a)

numpy.ndarray

numpy.ndarray

In [105]:
# 2-dimensional
b=np.array([[2,33,44],[55,66,77],[1,2,3]])
b,b.ndim

(array([[ 2, 33, 44],
        [55, 66, 77],
        [ 1,  2,  3]]), 2)

(array([[ 2, 33, 44],
        [55, 66, 77],
        [ 1,  2,  3]]), 2)

In [106]:
# 3-dimensional
c=np.array([
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,1,1],[2,2,2],[3,3,3]]
           ])
c,c.ndim

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]), 3)

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]), 3)

In [107]:
#getting the shape
a.shape,b.shape,c.shape

((3,), (3, 3), (2, 3, 3))

((3,), (3, 3), (2, 3, 3))

In [108]:
#getting the dimension
a.ndim,b.ndim,c.ndim

(1, 2, 3)

(1, 2, 3)

In [109]:
#getting the size of each array : no. of elements
a.size,b.size,c.size

(3, 9, 18)

(3, 9, 18)

In [110]:
#getting the datatype
a.dtype,b.dtype,c.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

(dtype('int64'), dtype('int64'), dtype('int64'))

In [111]:
#getting the total size of each array
a.nbytes,b.nbytes,c.nbytes

(24, 72, 144)

(24, 72, 144)

# 2. Creating the arrays
-----------------------------


In [112]:
array=np.array([2,4,5])
array

array([2, 4, 5])

array([2, 4, 5])

In [113]:
array.dtype

dtype('int64')

dtype('int64')

In [114]:
# creating an matrix of ones
print(np.ones(4,dtype='int'))
print(np.ones((3,3)))
print(np.ones_like(b))

[1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [115]:
# creating an matrix of zeros
print(np.zeros(4,dtype='int'))
print(np.zeros((3,3)))
print(np.zeros_like(b))

[0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [116]:
#identity matrix : np.eye(4)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
#fill matrix with certain value
np.full((3,4),100,dtype='U8')  #string of 100 in 3X4 matrix

array([['100', '100', '100', '100'],
       ['100', '100', '100', '100'],
       ['100', '100', '100', '100']], dtype='<U8')

array([['100', '100', '100', '100'],
       ['100', '100', '100', '100'],
       ['100', '100', '100', '100']], dtype='<U8')

In [118]:
#empty matrix : creates an unintialized array of certain size
np.empty((2,4))

array([[3.34417463e-316, 6.90754627e-310, 2.14321575e-312,
        2.46151512e-312],
       [6.90754625e-310, 6.90752352e-310, 6.90752352e-310,
        1.33511316e-306]])

array([[3.34417463e-316, 6.90754627e-310, 2.14321575e-312,
        2.46151512e-312],
       [6.90754625e-310, 6.90752352e-310, 6.90752352e-310,
        1.33511316e-306]])

# creating random matrix in numpy
--------------------------------------

In [119]:
np.random.rand(2,3) 
#creates a uniform distribution between (0,1]

array([[0.28589569, 0.85239509, 0.97500649],
       [0.88485329, 0.35950784, 0.59885895]])

array([[0.28589569, 0.85239509, 0.97500649],
       [0.88485329, 0.35950784, 0.59885895]])

In [120]:
np.random.random((3,3)) 

##creates a uniform distribution between (0,1]

'''
only difference between random and rand is the paramater style
'''

'\nonly difference between random and rand is the paramater style\n'

'\nonly difference between random and rand is the paramater style\n'

In [121]:
##  creates a uniform distribution between (low,high]
np.random.uniform(low=10,high=100,size=(3,4))

array([[22.8340283 , 94.04571695, 95.17418927, 64.2066992 ],
       [44.89896523, 42.68692037, 28.39107492, 34.90885553],
       [32.18822931, 25.62472016, 96.9948725 , 96.13113403]])

array([[22.8340283 , 94.04571695, 95.17418927, 64.2066992 ],
       [44.89896523, 42.68692037, 28.39107492, 34.90885553],
       [32.18822931, 25.62472016, 96.9948725 , 96.13113403]])

In [122]:
## Normal distribution between 0 and 1 i.e mean 0 and std. dev is 1
np.random.randn(2,5)

array([[ 1.52795302,  0.64720579, -0.67733661, -0.2650188 ,  0.74610644],
       [-3.13078483,  0.05962178, -0.87521111,  1.06487833, -0.57315265]])

array([[ 1.52795302,  0.64720579, -0.67733661, -0.2650188 ,  0.74610644],
       [-3.13078483,  0.05962178, -0.87521111,  1.06487833, -0.57315265]])

In [123]:
# Normal distribution of 10 and 20 i.e mean 10 and std. dev is 20
# number does not stay same on multiple executions
np.random.normal(10,20,(3,3))

array([[ -6.06556974,  31.85943254,  23.02555159],
       [ 53.21049576,  -2.78260135,   3.32624941],
       [  1.24796284, -28.11589762, -14.58038664]])

array([[ -6.06556974,  31.85943254,  23.02555159],
       [ 53.21049576,  -2.78260135,   3.32624941],
       [  1.24796284, -28.11589762, -14.58038664]])

In [124]:
## random integers between certain range
np.random.randint(2,10,(3,4))

array([[6, 6, 7, 3],
       [9, 2, 3, 2],
       [8, 6, 4, 2]])

array([[6, 6, 7, 3],
       [9, 2, 3, 2],
       [8, 6, 4, 2]])

In [125]:
## evenly spaced numbers between certain range
np.linspace(10,20,num=5)

array([10. , 12.5, 15. , 17.5, 20. ])

array([10. , 12.5, 15. , 17.5, 20. ])

In [126]:
# numbers of certain range
np.arange(10,20,3) # sttart,stop,step

array([10, 13, 16, 19])

array([10, 13, 16, 19])

In [127]:
## using random.seeed : number stays same irrespective of executions
np.random.seed(100)
np.random.random((4,4))

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378]])

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613],
       [0.00471886, 0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378]])

In [128]:
#using randomstate
r=np.random.RandomState(100)
r.randn(2,3)
#r.randomint()
#r.rand()

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884]])

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884]])

1. [Difference](https://stackoverflow.com/q/22994423/12210002) between np.random.seed() and np.randomState(seed) .

2. first one affects the state globally and sets it to that for all operations  .

3. while the latter one sets the state with the seed for that operation only. it returns a random object by which we can perform all the operations . 
  e.g : r.rand or r.randn etc.

4. meaning random.seed(0) [link1](https://stackoverflow.com/q/21494489/12210002) and [link2](https://stackoverflow.com/a/22639752/12210002)

# Accessing the elements of the array
---------------------------------

In [129]:
# to get the unique elementss
np.unique(c)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
# accessing the elements format : arr[dim,r,c...]
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [131]:
#suppose we want the [2,2,2] vector from c
# c is a 3-dim
c[1,1,:]

array([2, 2, 2])

array([2, 2, 2])

In [132]:
#suppose we want the middle coloumn of each matrix 2,5,8,1,2,3
c[:,:,1]

array([[2, 5, 8],
       [1, 2, 3]])

array([[2, 5, 8],
       [1, 2, 3]])

In [133]:
c[:,:2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 1],
        [2, 2]]])

array([[[1, 2],
        [4, 5]],

       [[1, 1],
        [2, 2]]])

In [134]:
#Another example
d=np.random.randint(0,100,(2,3,3,3))
d,d.ndim

(array([[[[ 4, 31,  1],
          [13, 83,  4],
          [91, 59, 67]],
 
         [[ 7, 49, 47],
          [65, 61, 14],
          [55, 71, 80]],
 
         [[ 2, 94, 19],
          [98, 63, 53],
          [27, 56, 30]]],
 
 
        [[[48, 47, 39],
          [38, 44, 18],
          [64, 56, 34]],
 
         [[53, 74, 17],
          [72, 13, 30],
          [17, 53, 68]],
 
         [[50, 91, 91],
          [83, 53, 78],
          [ 0, 13, 57]]]]), 4)

(array([[[[ 4, 31,  1],
          [13, 83,  4],
          [91, 59, 67]],
 
         [[ 7, 49, 47],
          [65, 61, 14],
          [55, 71, 80]],
 
         [[ 2, 94, 19],
          [98, 63, 53],
          [27, 56, 30]]],
 
 
        [[[48, 47, 39],
          [38, 44, 18],
          [64, 56, 34]],
 
         [[53, 74, 17],
          [72, 13, 30],
          [17, 53, 68]],
 
         [[50, 91, 91],
          [83, 53, 78],
          [ 0, 13, 57]]]]), 4)

In [135]:
#accessing the 2nd last matrix
d[1,1,:,:]

array([[53, 74, 17],
       [72, 13, 30],
       [17, 53, 68]])

array([[53, 74, 17],
       [72, 13, 30],
       [17, 53, 68]])

In [136]:
## Get the first 4 elements of innner arrays row wise
d[:,:,0,:]

array([[[ 4, 31,  1],
        [ 7, 49, 47],
        [ 2, 94, 19]],

       [[48, 47, 39],
        [53, 74, 17],
        [50, 91, 91]]])

array([[[ 4, 31,  1],
        [ 7, 49, 47],
        [ 2, 94, 19]],

       [[48, 47, 39],
        [53, 74, 17],
        [50, 91, 91]]])

In [137]:
##  Get the  4 elements of innner arrays column wise
d[:,:,:,0]

array([[[ 4, 13, 91],
        [ 7, 65, 55],
        [ 2, 98, 27]],

       [[48, 38, 64],
        [53, 72, 17],
        [50, 83,  0]]])

array([[[ 4, 13, 91],
        [ 7, 65, 55],
        [ 2, 98, 27]],

       [[48, 38, 64],
        [53, 72, 17],
        [50, 83,  0]]])

# Manipulating and comparing arrays
-------------------------------------

1. Use Python's methods (sum()) on Python datatypes and use NumPy's methods on NumPy arrays (np.sum()).

2.  Standard deviation and variance are measures of 'spread' of data.The higher standard deviation and the higher variance of data, the more spread out the values are.

The lower standard deviation and lower variance, 
the less spread out the values are.

    2.1. Standard deviation = a measure of how spread out a group of numbers is from the mean

    2.2.  Variance = measure of the average degree to which each number is different to the mean

    Higher variance = wider range of numbers 

    Lower variance = lower range of numbers



In [138]:
d=np.ones(3)
a,d

(array([1, 2, 3]), array([1., 1., 1.]))

(array([1, 2, 3]), array([1., 1., 1.]))

In [139]:
#addition,subtraction,multipication,division,floor_div
a+d,a-d,a*d,a/d,a//d,a**2

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1, 4, 9]))

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1, 4, 9]))

In [140]:
## same operation using np. way
np.add(a,d),np.subtract(a,d),np.multiply(a,d),np.divide(a,d),np.floor_divide(a,d)

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]))

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]),
 array([1., 2., 3.]))

In [141]:
np.exp(a),np.log(a),np.mod(a,d)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.        , 0.69314718, 1.09861229]),
 array([0., 0., 0.]))

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.        , 0.69314718, 1.09861229]),
 array([0., 0., 0.]))

In [142]:
#maxium and minium element and their index position by argmax an argmin
a,np.max(a),np.min(a),np.argmax(a),np.argmin(a)

(array([1, 2, 3]), 3, 1, 2, 0)

(array([1, 2, 3]), 3, 1, 2, 0)

In [143]:
#mean,median,variance,std.deviation,percentile
np.mean(a),np.median(a),np.var(a),np.std(a),np.percentile(a,90)

(2.0, 2.0, 0.6666666666666666, 0.816496580927726, 2.8000000000000003)

(2.0, 2.0, 0.6666666666666666, 0.816496580927726, 2.8000000000000003)

# reshaping and Transposing
---------------------------------

In [144]:
b.reshape((1,9))

array([[ 2, 33, 44, 55, 66, 77,  1,  2,  3]])

array([[ 2, 33, 44, 55, 66, 77,  1,  2,  3]])

In [145]:
b.reshape((9,1))

array([[ 2],
       [33],
       [44],
       [55],
       [66],
       [77],
       [ 1],
       [ 2],
       [ 3]])

array([[ 2],
       [33],
       [44],
       [55],
       [66],
       [77],
       [ 1],
       [ 2],
       [ 3]])

In [146]:
#transposing
b.reshape((9,1)).T

array([[ 2, 33, 44, 55, 66, 77,  1,  2,  3]])

array([[ 2, 33, 44, 55, 66, 77,  1,  2,  3]])

In [147]:
b.reshape((1,9)).transpose()

array([[ 2],
       [33],
       [44],
       [55],
       [66],
       [77],
       [ 1],
       [ 2],
       [ 3]])

array([[ 2],
       [33],
       [44],
       [55],
       [66],
       [77],
       [ 1],
       [ 2],
       [ 3]])

Dot Product
---------------------------------

In [150]:
m1=np.random.randint(10,20,(3,3))
m2=np.full((3,3),100)
m1,m2

(array([[14, 14, 15],
        [17, 16, 16],
        [12, 14, 12]]), array([[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]]))

In [151]:
m1*m2 #element wise multipication

array([[1400, 1400, 1500],
       [1700, 1600, 1600],
       [1200, 1400, 1200]])

In [152]:
np.multiply(m1,m2) #same

array([[1400, 1400, 1500],
       [1700, 1600, 1600],
       [1200, 1400, 1200]])

In [153]:
m1@m2 #matrix multipication ,sames as matmul

array([[4300, 4300, 4300],
       [4900, 4900, 4900],
       [3800, 3800, 3800]])

In [155]:
np.matmul(m1,m2)

array([[4300, 4300, 4300],
       [4900, 4900, 4900],
       [3800, 3800, 3800]])

In [0]:
# for dim > 3, how dot product happens
fourbyfour = np.array([
                       [1,2,3,4],
                       [3,2,1,4],
                       [5,4,6,7],
                       [11,12,13,14]
                      ])


twobyfourbythree = np.array([
                             [[2,3],[11,9],[32,21],[28,17]],
                             [[2,3],[1,9],[3,21],[28,7]],
                             [[2,3],[1,9],[3,21],[28,7]],
                            ])

In [157]:
fourbyfour.shape,twobyfourbythree.shape

((4, 4), (3, 4, 2))

In [158]:
res=np.dot(fourbyfour,twobyfourbythree)
res.shape

(4, 3, 2)

In [159]:
res

array([[[232, 152],
        [125, 112],
        [125, 112]],

       [[172, 116],
        [123,  76],
        [123,  76]],

       [[442, 296],
        [228, 226],
        [228, 226]],

       [[962, 652],
        [465, 512],
        [465, 512]]])

**dot product vs matmul** [link](https://stackoverflow.com/q/34142485/12210002)

1. for 1-d, dot product is same as inner product a*b
2. for 2-d, dot product is same as matmul or @ i.e matrix multipication
3. for dimension>2, it's evaluation process changes.(see the link and [doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html))



> np.dot(a,b)= sum(last axis of a * 2nd last axis of b)




In [160]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([3, 2, 1])

#dot product
vec1*vec2, np.dot(vec1,vec2)

(array([3, 4, 3]), 10)

# Sorting the arrays

In [162]:
b,c

(array([[ 2, 33, 44],
        [55, 66, 77],
        [ 1,  2,  3]]), array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]))

In [167]:
np.sort(b),np.sort(c)

(array([[ 2, 33, 44],
        [55, 66, 77],
        [ 1,  2,  3]]), array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]]))

In [168]:
np.argsort(a),np.argsort(b)

(array([0, 1, 2]), array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]))

In [169]:
#maxium and index of maxium element
np.max(b),np.argmax(b)

(77, 5)

## Practical Example

In [0]:

# Turn an image into a NumPy array
from matplotlib.image import imread

In [175]:
panda = imread("numpy-panda.png")
print(type(panda))

<class 'numpy.ndarray'>
